package chapter14.tricatch;

import javax.management.RuntimeErrorException;

public class BadIndex {
	public static final int SIZE = 10;
	public static void main(String[] args) {
		int[] array = new int[SIZE];
		
		int result=0;
		for(int i=0;i<array.length;i++) {
			array[i]=i;
		}
		try{
		result = array[12];
		System.out.println("프로그램 진행 중입니다.");
		}catch(ArrayIndexOutOfBoundsException a) {
			result = array[9];
			System.out.println("잘 맞췄어요(속았어요.). 당신은 성공했습니다.(사기당했습니다.) 결과값은 "+result);
			throw new RuntimeException();
		}finally {
			System.out.println("프로그램 진행이 끝났습니다.");
		}
		System.out.println("과연 이 문장이 실행이 될까요?"+result);
	}

}
